@startuml

class DataCollector {
    - connection: string
    + fetch_data(): DataFrame
}

class DataPreprocessor {
    + clean_data(): DataFrame
    + scale_data(): DataFrame
    + handle_missing_values(): DataFrame
}

class DataAnalyzer {
    - data_statistics: string
    + compute_statistics(): dict
}

class DataVisualizer {
    + graphs: Binary
    + plot_graph(): void
}

class DataSaver {
    + data_file: Binary
    + save_to_csv(): void
    + load_from_csv(): DataFrame
}

class ModelTrainer {
    + model_type: string
    + model_parameters: string
    + data_parameters: string
    + train_model(): Model
}

class ModelTester {
    + model_type: string
    + test_model(): dict
}

class ModelStorage {
    + model_file: Binary
    + save_model(): void
    + load_model(): Model
}

class ModelAnalyzer {
    + models_metrics: string
    + models_matrix: Binary
    + compute_models_metrics(): dict
}

class VoitingClassifierTrainer {
    + models: string
    + voiting_type: string
    + train_models(): void
}

class VoitingClassifierTester {
    + models: string
    + test_models(): dict
}

DataPreprocessor --|> DataCollector
DataAnalyzer --|> DataPreprocessor
DataVisualizer --|> DataAnalyzer
DataSaver --|> DataPreprocessor
ModelTrainer --|> DataSaver
ModelTester --|> ModelTrainer
ModelStorage --|> ModelTrainer
VoitingClassifierTrainer --|> ModelTrainer
VoitingClassifierTester --|> VoitingClassifierTrainer
ModelStorage --|> VoitingClassifierTrainer

ModelAnalyzer --> ModelTrainer
ModelAnalyzer --> ModelTester
ModelAnalyzer --> VoitingClassifierTrainer
ModelAnalyzer --> VoitingClassifierTester

@enduml
